version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.7

        working_directory: ~/repo

        steps:
          - checkout
          - run: sudo chown -R circleci:circleci /usr/local/bin
          - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
          - restore_cache:
              key: deps10-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          - run:
              command: |
                sudo pip install pipenv
                pipenv install
          - save_cache:
              key: deps10-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
              paths:
                - '.venv'
                - '/usr/local/bin'
                - '/usr/local/lib/python3.6/site-packages'

            - run:
                  name: run tests
                  command: |
                      coverage run ./manage.py test
                      codecov

            - store_artifacts:
                  path: test-reports
                  destination: test-reports
