# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
    build:
        docker:
            # specify the version you desire here
            # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
            - image: circleci/python:3.7

            # Specify service dependencies here if necessary
            # CircleCI maintains a library of pre-built images
            # documented at https://circleci.com/docs/2.0/circleci-images/
            # - image: circleci/postgres:9.4

        working_directory: ~/repo

        steps:
            - checkout
            - run: sudo chown -R circleci:circleci /usr/local/bin
            - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
            - restore_cache:
                  keys:
                      - pip-packages-v2-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
                      - pip-packages-v2-{{ .Branch }}-
                      - pip-packages-v2-
            - run:
                  command: |
                      sudo pip install pipenv
                      pipenv install coverage==4.5.4
                      pipenv install codecov
            - save_cache:
                  paths:
                      - 'Pipfile.lock'
                      - '.venv'
                      - '/usr/local/bin'
                      - '/usr/local/lib/python3.7/site-packages'
                  key: pip-packages-v2-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

            # run tests!
            # this example uses Django's built-in test-runner
            # other common Python testing frameworks include pytest and nose
            # https://pytest.org
            # https://nose.readthedocs.io
            - run:
                  name: run tests
                  command: |
                      pipenv shell
                      python manage.py test

            - store_artifacts:
                  path: test-reports
                  destination: test-reports
